{% set version = "1.4.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-skynet
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/skynet_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/skynet/skynet_{{ version }}.tar.gz
  sha256: 7df92f52db49da617b7992a876285c5f20c2884f97fae56a8b5be731cf6fd6f6

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcurl
    - r-data.table
    - r-dplyr
    - r-geosphere
    - r-ggplot2
    - r-ggrepel
    - r-httr
    - r-igraph
    - r-leaflet
    - r-maps
    - r-stringr
  run:
    - r-base
    - r-rcurl
    - r-data.table
    - r-dplyr
    - r-geosphere
    - r-ggplot2
    - r-ggrepel
    - r-httr
    - r-igraph
    - r-leaflet
    - r-maps
    - r-stringr

test:
  commands:
    - $R -e "library('skynet')"           # [not win]
    - "\"%R%\" -e \"library('skynet')\""  # [win]

about:
  home: https://github.com/FilipeamTeixeira/skynet
  license: MIT
  summary: A flexible tool that allows generating bespoke air transport statistics for urban studies based on publicly available data from the Bureau of Transport Statistics (BTS) in the United States <https://www.transtats.bts.gov/databases.asp?Mode_ID=1&Mode_Desc=Aviation&Subject_ID2=0>.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor
