appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: wOt9BblKev5n6xySz5sv/MUStI5t3/POg+jJrJZGeIx/+FBXlwY3+uugWh+4hTMGop9W1VrN6fxtQwq5zKotACea+8qdjd3/GfB8q5YAEXse5UMJYvsSlLqYrryXoFe6xUi8tf+FZmsdBkOVPEABYNe/QNXzaQ2CNbFlnfiUh8+TmMd+DdJo1cW0cPAqbwaRjDATsHZ94AdlLlClrhWTjWqE6v/Zprd1Y5Y7m93OxzKc8W17SbVetRgoGeRZzWpYFDXLG8P/nOjT9VvenHKnwePdAmCPU5hLlOjogrw3YSz83hGWU7U8hQ9yb9pGnFkoz8dnUO1CDFvQ/2FQB7LR8DMd5Sw/iP8kXwGY/Wu8KKvl+wyVVZSlbhM9D3PPQ2xi11kNiEToNVQ7C/l3tSrWPfl3DlTD6HnGxbt+V8K2ne5OPIAKHvQRldMTvH5P4inWEZqhX767aIHTk0h5+V/IEDJXOryJUTZ3ZECCylRI6BiE1EEEgTxIOJkM2otn6FGjgNiBF5M9hOFP8KTppqaDmt70EYhyEatxszmGF8BMxk6eCYGW3k0aK6ih/TJDGDgxNA/C1Ze2PHSSqOmmp/n+xWOffp+vAk9hS1YcJRVbqXX0Dn0Q7hOpl5Yvw4iUiRxPVrCTqRyvcZQN8v/eEeAfrOXbo9OwVARO0AdIDxuKp1g=}
bot:
  automerge: true
